#!/bin/bash

###################################
#
#              EGIDA
#
###################################


# ============ CONSTS ===============
set -e
BASEDIR=$(dirname "$0")

apt install knockd
pip3 install -r "$BASEDIR/requirements.txt"
